# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd6f405f1ddfb7f79605f0a4373e7fd2f5a77ef1f2785d9bfc1fcefd552b8e72b7a2b557d63b6773257b7c4427c6980d6212b3a641fdfef096b3063b349816ae

test:
  secret_key_base: 62679111730f9d1b952fbbcdf796e1112f6e67793d80d0d0172982770ab3987047b6e23c73fdeb5bfa1569625f90ae411338df43e5bff164b0eea8c5b69e9554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
